### ISSUE TITLE
ArrayBuffer views should be recognized as binary data and treated respectively 

### ISSUE THREAD

**Issue by Gozala** [ipld/js-ipld-dag-cbor#128]
At the moment `Uint8Array` (or any other view of `ArrayBuffer` seems to be treated as array of numbers)

https://github.com/ipld/js-ipld-dag-cbor/blob/5d3389abcd1d504423568c4b5cb46b3ab4d4b1f9/src/util.js#L37-L48

This causes issues when things are moved across the message channel, because even fields that were `Buffer`'s come up as `Uint8Array`s on the other end. For this reason I would like to propose a change which would treat `Uint8Array` (and I'm inclined to suggest other `ArrayBuffer` views as well) as a binary data instead (same as `Buffer`s is treated today).

It is worth pointing out that `ArrayBuffer` itself will appear as `{byteLength:number}` which I don't think is ideal, but probably out of scope.

**Comment by vmx** [comment]
Fixed by #129.

**Comment by vmx** [comment]
I already published it right away, it's v0.15.3.
