### ISSUE TITLE
ipld.multihash should allow passing in different functions

### ISSUE THREAD

**Issue by jbenet** [ipld/js-ipld-dag-cbor#15]
right now `ipld.multihash` [hard-codes sha256](https://github.com/ipfs/js-ipld/blob/master/src/multihash.js#L12). it should be flexible, like multihash.

**Comment by jbenet** [comment]
cc @wanderer

**Comment by diasdavid** [comment]
This request was with regards to the old old IPLD (previous to IPLD Format). Created a issue to track the addition of this feature to the interface-ipld-format here: https://github.com/ipld/interface-ipld-format/issues/2
