### ISSUE TITLE
Update readme and description

### ISSUE THREAD

**Issue by dignifiedquire** [ipld/js-ipld-dag-cbor#27]
They currently still point to the generic `js-ipld`

**Comment by RichardLitt** [comment]
Also, any project in IPLD should be labelled as 'project IPLD' in the badge at the top.

**Comment by diasdavid** [comment]
@RichardLitt could you help us make sure all IPLD modules are polished? Thank you :)

**Comment by RichardLitt** [comment]
@diasdavid Yes, I can. :)
