### ISSUE TITLE
Switch to `borc` caused a Bug when using Buffers

### ISSUE THREAD

**Issue by diasdavid** [ipld/js-ipld-dag-cbor#37]
Context: https://github.com/ipld/js-ipld-dag-cbor/commit/3164a8130d0de5dc4e65ff1430138fe60a8c9052#commitcomment-20654929

**Comment by diasdavid** [comment]
all good now, thank you for fixing it @dignifiedquire <3

**Comment by dignifiedquire** [comment]
This was the fix for future reference: https://github.com/dignifiedquire/borc/commit/4ed9a69cfe935acb65f91eb9d5ac859e6c6bd759
