### ISSUE TITLE
dagCBOR.DAGNode.create?

### ISSUE THREAD

**Issue by imars** [ipld/js-ipld-dag-cbor#61]
Is there an equivalent dagCBOR.DAGNode.create to the protobuf version dagPB.DAGNode.create?

**Comment by vmx** [comment]
I'm not sure I understand you quersion. With the CBOR encoding you can encode any JSON you like. What are you trying to do?

**Comment by imars** [comment]
We're trying to write CBOR encoded DAG nodes to IPFS, directly. It seems like it ought to be simply a matter of encoding the fields?

**Comment by vmx** [comment]
Even `dagPB.DAGNode.create` isn't a thing anymore, hence I'm closing this issue.
