### ISSUE TITLE
Should not encode node's larger than the implementation can decode.

### ISSUE THREAD

**Issue by mikeal** [ipld/js-ipld-dag-cbor#72]
There's a few threads in different places about what the default size node size max should be and what kinds of restrictions we should place on node size in general.

Regardless of where we end up with that, the implementation should not encode nodes that are larger than it is configured to decode, which is what it does now.

**Comment by chafey** [comment]
cbor.encode() does not currently support a max size.  The best we can do right now is encode and throw if it is too big.  See PR https://github.com/ipld/js-ipld-dag-cbor/pull/120

**Comment by mikeal** [comment]
When this bug was logged it wasn’t against the “maxSize” option the way that it is now, which is mostly for the consumer to be able to protect against large memory consumption, there was a hard limit in the library on what could be decoded. We actually “fixed” the decoder side of this, so there isn’t really a size the decoder can’t decode any longer, as long as you have enough memory it can handle a block as big as you’ve got if you set the maxSize high enough.

There’s still limitations on block size elsewhere, mostly at the transport layer, but those are no longer enforced by this library by default.

We can close this now. But I want to ping @rvagg just so that he’s aware of this issue and the history since he’s writing a new `cbor` encoder/decoder.

Also, the PR’s related to this are still good and valid. They are just fixing something that isn’t actually this bug as it was originally logged 😁
